on: [push,pull_request]
jobs:
  maanam:
    steps:
      - run: echo Hello World
      - uses: actions/checkout@v2
      - run: g++ 02.12.cpp -o main
      - run: ./main
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [macOS-latest, windows-latest, ubuntu-latest] 
    
